### ISSUE TITLE
Redirects adds unnecessary extra slash

### ISSUE THREAD

**Issue by UlrichThomasGabor** [makinacorpus/static-passthrough-bundle#4]
Something here
https://github.com/makinacorpus/static-passthrough-bundle/blob/master/src/Controller/StaticPassthroughController.php#L45-L66
is wrong. A URL like `http://example.org/docs/myDir/` is redirected to `http://example.org/docs/myDir//index.html`.

Maybe just change line 63 to `\rtrim($request->getPathInfo(), '/')`?

**Comment by SimonMellerin** [comment]
Sorry I hadn't enabled notifications on this repo, I missed issues...

> Maybe just change line 63 to \rtrim($request->getPathInfo(), '/')?

Yep that's it ! I'm gonna fix that

**Comment by UlrichThomasGabor** [comment]
@SimonMellerin Hm. You need help with that?

**Comment by SimonMellerin** [comment]
Sorry for the delay, it's fix now

Shipped with version 0.1.12

**Comment by UlrichThomasGabor** [comment]
Thanks!
