### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by yaziderman** [makinacorpus/static-passthrough-bundle#5]
With Symfony CLI version 5.4.16, Composer version 2.3.10 and php8.1, I am not able to install the package:

$ composer require makinacorpus/static-passthrough-bundle

Using version ^0.1.8 for makinacorpus/static-passthrough-bundle
./composer.json has been updated
Running composer update makinacorpus/static-passthrough-bundle
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "6.1.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires makinacorpus/static-passthrough-bundle ^0.1.8 -> satisfiable by makinacorpus/static-passthrough-bundle[0.1.8].
    - makinacorpus/static-passthrough-bundle 0.1.8 requires symfony/framework-bundle ^4.3.3|^5.0|^5.1 -> found symfony/framework-bundle[v4.3.3, ..., v4.4.47, v5.0.0, ..., v5.4.14] but it conflicts with your root composer.json require (6.1.*).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require makinacorpus/static-passthrough-bundle:*" to figure out if any version is installable, or "composer require makinacorpus/static-passthrough-bundle:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by SimonMellerin** [comment]
Sorry I hadn't enabled notifications on this repo, I missed issues...

Should be good now for this problem, we updated the bundle to be  compatible with Symfony 6
